language: java
sudo: required
dist: xenial

jdk:
- openjdk8

addons:
  apt_packages:
  - p7zip

cache:
  directories:
  - download/qt

before_install:
- openssl aes-256-cbc -K "$encrypted_14c4db58b9e2_key" -iv "$encrypted_14c4db58b9e2_iv" -in secret/jpc-android.ks.enc -out secret/jpc-android.ks -d
- export ANDROID_HOME="/home/android"
- export ANDROID_SDK_ROOT="$ANDROID_HOME"
- export ANDROID_NDK_ROOT="$ANDROID_HOME/android-ndk-r20"
- export QTDIR="/home/qt/work/install"
- export PATH="$QTDIR/bin:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"

install:
# create download directories
- mkdir -p download/qt
# install Android SDK
- sudo install -d -m777 "$ANDROID_HOME"
- wget -q -c -O {download,https://dl.google.com/android/repository}/sdk-tools-linux-4333796.zip
- unzip -q -d "$ANDROID_HOME" download/sdk-tools-linux-4333796.zip
- mkdir -p ~/.android
- touch ~/.android/repositories.cfg
- yes | sdkmanager --licenses > /dev/null
- yes | sdkmanager "tools" "platform-tools" > /dev/null
- yes | sdkmanager "platforms;android-29" > /dev/null
- yes | sdkmanager "build-tools;29.0.1" > /dev/null
# install Android NDK
- wget -q -c -O {download,https://dl.google.com/android/repository}/android-ndk-r20-linux-x86_64.zip
- unzip -q -d "$ANDROID_HOME" download/android-ndk-r20-linux-x86_64.zip
# install Qt
- sudo install -d -m777 /home/qt
# Qt for Android ARMv7
- cd download/qt
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_armv7/5.13.0-0-201906171620qtbase-Linux-RHEL_7_6-Clang-Android-Android_ANY-ARMv7.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_armv7/5.13.0-0-201906171620qtandroidextras-Linux-RHEL_7_6-Clang-Android-Android_ANY-ARMv7.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_armv7/5.13.0-0-201906171620qttools-Linux-RHEL_7_6-Clang-Android-Android_ANY-ARMv7.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_armv7/5.13.0-0-201906171620qtdeclarative-Linux-RHEL_7_6-Clang-Android-Android_ANY-ARMv7.7z
- cd ../..
# Qt for Android X86
- cd download/qt
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_x86/5.13.0-0-201906171620qtbase-Linux-RHEL_7_6-Clang-Android-Android_ANY-X86.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_x86/5.13.0-0-201906171620qtandroidextras-Linux-RHEL_7_6-Clang-Android-Android_ANY-X86.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_x86/5.13.0-0-201906171620qttools-Linux-RHEL_7_6-Clang-Android-Android_ANY-X86.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_x86/5.13.0-0-201906171620qtdeclarative-Linux-RHEL_7_6-Clang-Android-Android_ANY-X86.7z
- cd ../..
# Qt for Android ARM64
- cd download/qt
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_arm64_v8a/5.13.0-0-201906171620qtbase-Linux-RHEL_7_6-Clang-Android-Android_ANY-ARM64.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_arm64_v8a/5.13.0-0-201906171620qtandroidextras-Linux-RHEL_7_6-Clang-Android-Android_ANY-ARM64.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_arm64_v8a/5.13.0-0-201906171620qttools-Linux-RHEL_7_6-Clang-Android-Android_ANY-ARM64.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_arm64_v8a/5.13.0-0-201906171620qtdeclarative-Linux-RHEL_7_6-Clang-Android-Android_ANY-ARM64.7z
- cd ../..
# Qt for Android X86_64
- cd download/qt
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_x86_64/5.13.0-0-201906171620qtbase-Linux-RHEL_7_6-Clang-Android-Android_ANY-X86_64.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_x86_64/5.13.0-0-201906171620qtandroidextras-Linux-RHEL_7_6-Clang-Android-Android_ANY-X86_64.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_x86_64/5.13.0-0-201906171620qttools-Linux-RHEL_7_6-Clang-Android-Android_ANY-X86_64.7z
- wget -q -c https://download.qt.io/online/qtsdkrepository/linux_x64/android/qt5_5130/qt.qt5.5130.android_x86_64/5.13.0-0-201906171620qtdeclarative-Linux-RHEL_7_6-Clang-Android-Android_ANY-X86_64.7z
- cd ../..

script:
# prepare Qt Android ARMv7
- for f in download/qt/*-ARMv7.7z; do 7zr x -o/home/qt "$f" > /dev/null; done
- mkdir -p /home/qt/work
- ln -s ../5.13.0/android_armv7 /home/qt/work/install
- sed -i 's/^QT_EDITION =.*/QT_EDITION = OpenSource/' /home/qt/work/install/mkspecs/qconfig.pri
- sed -i 's/^QT_LICHECK =.*/QT_LICHECK =/' /home/qt/work/install/mkspecs/qconfig.pri
# build Android ARMv7
- mkdir -p build
- cd build
- QMAKESPEC="$QTDIR/mkspecs/android-clang" qmake CONFIG+=release QMAKE_LINK+=-nostdlib++ ../mpe-surface.pro
- cd ..
- make -C build install INSTALL_ROOT=android-build
- androiddeployqt --input build/android-libmpe-surface.so-deployment-settings.json --output build/android-build --gradle --sign secret/jpc-android.ks jpc-android --storepass "$KEYSTORE_PASS"
- install -D -m 644 build/android-build/build/outputs/apk/release/android-build-release-signed.apk releases/mpe-surface-android_armv7.apk
- rm -rf build
- rm -rf /home/qt/*
# prepare Qt Android X86
- for f in download/qt/*-X86.7z; do 7zr x -o/home/qt "$f" > /dev/null; done
- mkdir -p /home/qt/work
- ln -s ../5.13.0/android_x86 /home/qt/work/install
- sed -i 's/^QT_EDITION =.*/QT_EDITION = OpenSource/' /home/qt/work/install/mkspecs/qconfig.pri
- sed -i 's/^QT_LICHECK =.*/QT_LICHECK =/' /home/qt/work/install/mkspecs/qconfig.pri
# build Android X86
- mkdir -p build
- cd build
- QMAKESPEC="$QTDIR/mkspecs/android-clang" qmake CONFIG+=release QMAKE_LINK+=-nostdlib++ ../mpe-surface.pro
- cd ..
- make -C build install INSTALL_ROOT=android-build
- androiddeployqt --input build/android-libmpe-surface.so-deployment-settings.json --output build/android-build --gradle --sign secret/jpc-android.ks jpc-android --storepass "$KEYSTORE_PASS"
- install -D -m 644 build/android-build/build/outputs/apk/release/android-build-release-signed.apk releases/mpe-surface-android_x86.apk
- rm -rf build
- rm -rf /home/qt/*
# prepare Qt Android ARM64
- for f in download/qt/*-ARM64.7z; do 7zr x -o/home/qt "$f" > /dev/null; done
- mkdir -p /home/qt/work
- ln -s ../5.13.0/android_arm64_v8a /home/qt/work/install
- sed -i 's/^QT_EDITION =.*/QT_EDITION = OpenSource/' /home/qt/work/install/mkspecs/qconfig.pri
- sed -i 's/^QT_LICHECK =.*/QT_LICHECK =/' /home/qt/work/install/mkspecs/qconfig.pri
# build Android ARM64
- mkdir -p build
- cd build
- QMAKESPEC="$QTDIR/mkspecs/android-clang" qmake CONFIG+=release QMAKE_LINK+=-nostdlib++ ../mpe-surface.pro
- cd ..
- make -C build install INSTALL_ROOT=android-build
- androiddeployqt --input build/android-libmpe-surface.so-deployment-settings.json --output build/android-build --gradle --sign secret/jpc-android.ks jpc-android --storepass "$KEYSTORE_PASS"
- install -D -m 644 build/android-build/build/outputs/apk/release/android-build-release-signed.apk releases/mpe-surface-android_arm64.apk
- rm -rf build
- rm -rf /home/qt/*
# prepare Qt Android X86_64
- for f in download/qt/*-X86_64.7z; do 7zr x -o/home/qt "$f" > /dev/null; done
- mkdir -p /home/qt/work
- ln -s ../5.13.0/android_x86_64 /home/qt/work/install
- sed -i 's/^QT_EDITION =.*/QT_EDITION = OpenSource/' /home/qt/work/install/mkspecs/qconfig.pri
- sed -i 's/^QT_LICHECK =.*/QT_LICHECK =/' /home/qt/work/install/mkspecs/qconfig.pri
# build Android X86_64
- mkdir -p build
- cd build
- QMAKESPEC="$QTDIR/mkspecs/android-clang" qmake CONFIG+=release QMAKE_LINK+=-nostdlib++ ../mpe-surface.pro
- cd ..
- make -C build install INSTALL_ROOT=android-build
- androiddeployqt --input build/android-libmpe-surface.so-deployment-settings.json --output build/android-build --gradle --sign secret/jpc-android.ks jpc-android --storepass "$KEYSTORE_PASS"
- install -D -m 644 build/android-build/build/outputs/apk/release/android-build-release-signed.apk releases/mpe-surface-android_x86_64.apk
- rm -rf build
- rm -rf /home/qt/*

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: releases/*
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

env:
  global:
  - secure: VRJ4GAftmgO1cfqOdWsYo1edn9tOMQeo2cyTEjqb2x2+ub+blX5nu6Di3h9G5HpLLQ057bTb06VcS0NmA8O0aOHcCglws7h31RsxoUYsy/2WG8G7i1O+sMPget7hzCc+xNk2lE7vmBDnyvs9kMxFqjwqbc31oQQFnoPiS4Hgz1VSj1PM+qKsUVK/gUoWZYd6jm/knflvDQlP0g58ihc+5F14XtnpXXtAJcqX1rnd9SOCges6uJAR21pFpXYPbuGLSBm70XB4omcBLtzUzZOvEwsz8efJtLXjookWcRKHR54RpxPIX12OLMRBQofnyLmvPCq34hYHr/y9SSTot4WjgniERLy7IWURdOwZs+z4+5z4buQPe++b8hi7BP2PvTl0Y9c9XTnzqCe6euV+f1goWcno88mJS2UYRLLgI6CxlOXNb0+NDigKZ28mf3ggDJkeMDoxnVacABZLRyuq+WRV6E98Ts+ZcMRs01ilVpnZ7BXVWJsWPRv9ca4yZHrYqfi0+VpTp6m9psECjVxadbeagp2q9E8d4j514A0hGfpORwFUaKsXwGAN9g7TkqGD6VB0uVr3nIhCz8hOR1u0nA4B2GM/NmG8mLCfTJJl4p5KBQNRyE8OYTZMoHMRJjWnSc4Xmri3fUqNcxRXxZVsUSmM1NDZV6ID8X6W06Xx2lC3ewo=
  - secure: OIcrW6Pk34XwXx+4lqkiU3Aq2yHoXU1ZQaY1yIV+T1uTTJD2qlXwUijBivfFMb6Ute9cnr5CKRswJHC42yLOqsjgbQyrq/iRexOuXq+Taqbg2/XXj0XtG2kwQXVrcbVd/6KY/GBauhdtHzCflKI44lbwc2bZx42zm4RfR9Ii928hh9D9h2SwNYTbG8U0bvr3f6H+F2NbIa4qfTyky3MTmWp4z4j+e1hIlB7SVC/zM4lVAto7X0EmstVThjiW9grujYeuaG0sVQxrmwk5J0GKhWteSBsvR/cbvr3Eanu3klLj12hPKeCxh164czj08xz55ECgBeWcX27JguPgCIJbyepCb7RLIFEevjsjr+Ewtx1oq6Qi/DNPjac1Toip9JjoMPeEMtdNyYXOGMlhEFXC1ZHYcXrOb41fg1uOtJG0JDANsR4WkbLejDYAijdKgJ7zkuQH1Dp4c9tb7MMTtI+L36tk+f2gikNS+Vz/4Ej40+7JhzHrJxeTAI176VV8z4r/EAuzq87stgSFiUyrIyMg52IrkKyFfX7FSx6Ue3dQ+oaiCdXR5Kt3ENDRCTroR5dAd8WeS73Sk1VtsQH2LYPULv0XBDSbKUjQIgVaGEqNRsyPblv9Ggd3V72PDTAPVoOdiVttJbtikminPC0q6GBaL+xj7o1eyOhZbgmU9owaE7Y=
